In [1]:
# 패키지에서 필요한 모듈을 모두 불러옴
from package import *
from tqdm import tqdm

In [2]:
conn = get_db_connection()
cursor = conn.cursor()

cursor.execute(
    "select table_schema from information_schema.tables group by table_schema;"
)

col = cursor.description
col_list = [col[i][0] for i in range(len(col))]
df = pd.DataFrame(cursor.fetchall(),columns = col_list)

df
# corp_gongsi_meta
# corp_stock_price

         TABLE_SCHEMA
0               mysql
1  information_schema
2  performance_schema
3                 sys
4    corp_gongsi_meta
5    corp_stock_price

         TABLE_SCHEMA
0    corp_gongsi_meta
1    corp_stock_price
2  information_schema
3               mysql
4  performance_schema
5                 sys

In [7]:
cursor.execute(
    "select * from information_schema.tables where table_schema ='corp_gongsi_meta';"
)

col = cursor.description
col_list = [col[i][0] for i in range(len(col))]
df_ = pd.DataFrame(cursor.fetchall(),columns = col_list)

df_ # 2308개 테이블
df_
df_[df_['TABLE_NAME']=='tmp']

,TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,TABLE_TYPE,ENGINE,VERSION,ROW_FORMAT,TABLE_ROWS,AVG_ROW_LENGTH,DATA_LENGTH,...,INDEX_LENGTH,DATA_FREE,AUTO_INCREMENT,CREATE_TIME,UPDATE_TIME,CHECK_TIME,TABLE_COLLATION,CHECKSUM,CREATE_OPTIONS,TABLE_COMMENT
0,def,corp_gongsi_meta,3s,BASE TABLE,InnoDB,10,Dynamic,85,578,49152,...,0,0,None,2022-03-24 16:55:00,None,None,utf8_unicode_ci,None,,
1,def,corp_gongsi_meta,aj네트웍스,BASE TABLE,InnoDB,10,Dynamic,131,750,98304,...,0,0,None,2022-03-24 16:53:57,None,None,utf8_unicode_ci,None,,
2,def,corp_gongsi_meta,ak홀딩스,BASE TABLE,InnoDB,10,Dynamic,233,632,147456,...,0,0,None,2022-03-24 16:53:39,None,None,utf8_unicode_ci,None,,
3,def,corp_gongsi_meta,aps홀딩스,BASE TABLE,InnoDB,10,Dynamic,134,611,81920,...,0,0,None,2022-03-24 16:55:00,None,None,utf8_unicode_ci,None,,
4,def,corp_gongsi_meta,ap시스템,BASE TABLE,InnoDB,10,Dynamic,104,630,65536,...,0,0,None,2022-03-24 16:55:00,None,None,utf8_unicode_ci,None,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2304,def,corp_gongsi_meta,흥국에프엔비,BASE TABLE,InnoDB,10,Dynamic,103,795,81920,...,0,0,None,2022-03-24 16:55:23,None,None,utf8_unicode_ci,None,,
2305,def,corp_gongsi_meta,흥국화재,BASE TABLE,InnoDB,10,Dynamic,88,558,49152,...,0,0,None,2022-03-24 16:54:17,None,None,utf8_unicode_ci,None,,
2306,def,corp_gongsi_meta,흥아해운,BASE TABLE,InnoDB,10,Dynamic,201,733,147456,...,0,0,None,2022-03-24 16:53:49,None,None,utf8_unicode_ci,None,,
2307,def,corp_gongsi_meta,희림,BASE TABLE,InnoDB,10,Dynamic,103,636,65536,...,0,0,None,2022-03-24 16:55:14,None,None,utf8_unicode_ci,None,,
2308,def,corp_gongsi_meta,힘스,BASE TABLE,InnoDB,10,Dynamic,184,623,114688,...,0,0,None,2022-03-24 16:55:05,None,None,utf8_unicode_ci,None,,

In [5]:
it = df_[df_['TABLE_NAME'] != 'tmp']['TABLE_NAME']

In [33]:
for i in it:
    print(i,end=',')

3s,aj네트웍스,ak홀딩스,aps홀딩스,ap시스템,ap위성,bgf,bgf리테일,bngt,bnk금융지주,byc,cbi,cj,cj cgv,cj enm,cj 바이오사이언스,cj대한통운,cj씨푸드,cj제일제당,cj프레시웨이,cmg제약,cnh,cnt85,cowon,cs,csa 코스믹,cs홀딩스,db,db금융스팩8호,db금융투자,db손해보험,db하이텍,dgb금융지주,dl,dl건설,dms,drb동일,dsc인베스트먼트,dsr,dsr제강,e1,edgc,eg,emw,esr켄달스퀘어리츠,es큐브,f&f 홀딩스,fsn,gh신소재,gkl,grt,gs,gst,gs건설,gs글로벌,gs리테일,hb솔루션,hb테크놀러지,hdc,hdc랩스,hdc현대ep,hdc현대산업개발,hj중공업,hk이노엔,hlb,hlb생명과학,hlb제약,hlb테라퓨틱스,hmm,hrs,hsd엔진,ibks제12호스팩,ibks제13호스팩,imbc,isc,itx-ai,jb금융지주,jtc,jw생명과학,jw신약,jw중외제약,jw홀딩스,jyp ent.,kbi메탈,kb금융,kb오토시스,kcc건설,kci,kc그린홀딩스,kc코트렐,kd,kec,kg ets,kg동부제철,kg모빌리언스,kg이니시스,kg케미칼,kh e&t,kh 일렉트론,kh 필룩스,kh바텍,kisco홀딩스,kmh,kmh하이텍,knn,kpx생명과학,kpx케미칼,kpx홀딩스,kr모터스,kss해운,ktb투자증권,ktcs,ktis,kt서브마린,lf,lg,lg디스플레이,lg생활건강,lg유플러스,lg이노텍,lg전자,lg헬로비전,lg화학,lig넥스원,ls,ls네트웍스,ls전선아시아,lx세미콘,lx인터내셔널,lx하우시스,mh에탄올,naver,new,ne능률,nhn벅스,nhn한국사이버결제,nh투자증권,nh프라임리츠,nice,nice평가정보,ni스틸,oci,pi첨단소재,pn풍년,rfhic,rf머트리얼즈,s&k폴리텍,s-oil,sbi인베스트먼트,sbi핀테크솔루션즈,sbs,sbs콘텐츠허브,sci평가정보,sdn,sfa반도체,sg,sg&g,sga,sga솔루션즈,sgc에너지,sgc이테크건설,sg글로벌,sg세계물산,shd,sh에너지화학,simpac,sk,sk5호스팩,sk6호스팩,skc,sk가스,sk네트웍스,sk디스커버리,sk디앤디,sk렌터카,sk바이오사이언스,sk아이이테크놀로지,sk이노베이션,sk증권,sk케미칼,sk텔레콤,sk하이닉스,sm c&c,sm life design,snk,snt모티브,snt에너지,snt중공업,snt홀딩스,spc삼립,stx,stx엔진,stx중공업,sun&l,sv인베스트먼트,tcc스틸,the e&m,the midong,thq,tj미디어,tpc,ts인베스트먼트,ts트릴리온,tym,uci,wi,wiscom,ybm넷,yg plus,ytn,yw,가비아,가온미디어,가온전선,감성코퍼레이션,강남제비스코,강스템바이오텍,강원랜드,강원에너지,갤럭시아머니트리,갤럭시아에스엠,경남스틸,경남제약,경남제약헬스케어,경농,경동나비엔,경동도시가스,경동인베스트,경동제약,경방,경보제약,경인양행,경인전자,경창산업,계룡건설산업,계양전기,고려산업,고려시멘트,고려신용정보,고려아연,고려제강,고려제약,고바이오랩,고영,골드앤에스,골드퍼시픽,골든센츄리,골프존,골프존뉴딘홀딩스,광동제약,광림,광명전기,광전자,광주신세계,광진실업,교보10호기업인수목적,교보9호스팩,교보증권,교촌에프앤비,구영테크,국도화학,국동,국보,국보디자인,국순당,국영지앤엠,국일신동,국일제지,국전약품,국제약품,그리티,그린케미칼,그린플러스,극동유화,글로벌에스엠,글로벌텍스프리,글로본,금강공업,금강철강,금비,금양,금호건설,금호석유화학,금호에이치티,금호전기,금호타이어,금화피에스시,기가레인,기산텔레콤,기신정기,기아,기업은행,까뮤이앤씨,까스텔바작,깨끗한나라,나노,나노브릭,나노스,나노신소재,나노씨엠에스,나노엔텍,나노캠텍,나라엠앤디,나무가,나무기술,나스미디어,나우ib,나이벡,나이스디앤비,나이스정보통신,나인테크,남광토건,남선알미늄,남성,남양유업,남해화학,남화산업,남화토건,내츄럴엔도텍,네오리진,네오셈,네오오토,네오위즈,네오위즈홀딩스,네오크레마,네오티스,네오팜,네오펙트,네온테크,네이블커뮤니케이션즈,네이처셀,네패스,네패스아크,넥센,넥센타이어,넥스턴바이오,넥스트bt,넥스트사이언스,넥스트아이,넥스틴,넥슨지티,넵튠,넷게임즈,넷마블,노랑풍선,노루페인트,노루홀딩스,노바렉스,노바텍,노터스,녹십자,녹십자엠에스,녹십자웰빙,녹십자홀딩스,녹원씨엔아이,농심,농심홀딩스,농업회사법인아시아종묘,농우바이오,누리플랜,누리플렉스,뉴로스,뉴보텍,뉴인텍,뉴지랩파마,뉴트리,뉴파워프라즈마,뉴프렉스,다나와,다날,다믈멀티미디어,다보링크,다산네트웍스,다스코,다우기술,다우데이타,다원시스,다이나믹디자인,대교,대구백화점,대덕,대덕전자,대동,대동금속,대동기어,대동스틸,대동전자,대륙제관,대림비앤코,대림제지,대림통상,대명소노시즌,대모,대보마그네틱,대봉엘에스,대상,대상홀딩스,대성미생물,대성산업,대성에너지,대성엘텍,대성창투,대성파인텍,대성홀딩스,대신밸런스제7호스팩,대신밸런스제8호스팩,대신정보통신,대신증권,대아티아이,대양금속,대양전기공업,대양제지,대영포장,대우건설,대우부품,대우조선해양,대웅,대웅제약,대원,대원강업,대원미디어,대원산업,대원전선,대원제약,대원화성,대유,대유에이텍,대유에이피,대유플러스,대정화금,대주산업,대주전자재료,대창,대창단조,대창솔루션,대창스틸,대한과학,대한광통신,대한그린파워,대한뉴팜,대한방직,대한약품,대한유화,대한전선,대한제강,대한제당,대한제분,대한항공,대한해운,대한화섬,대현,대호에이엘,대호특수강,대화제약,더네이쳐홀딩스,더블유게임즈,더블유에스아이,더존비즈온,덕산네오룩스,덕산테코피아,덕산하이메탈,덕성,덕신하우징,덕양산업,덕우전자,데브시스터즈,데이타솔루션,덱스터,덴티스,덴티움,도이치모터스,도화엔지니어링,동구바이오제약,동국s&c,동국산업,동국알앤에스,동국제강,동국제약,동남합성,동방,동방선기,동방아그로,동부건설,동서,동성제약,동성케미컬,동성화인텍,동신건설,동아쏘시오홀딩스,동아에스티,동아엘텍,동아지질,동아타이어,동아화성,동양,동양고속,동양생명,동양에스텍,동양이엔피,동양철관,동양파일,동양피스톤,동우팜투테이블,동운아나텍,동원f&b,동원개발,동원금속,동원산업,동원수산,동원시스템즈,동일고무벨트,동일금속,동일기연,동일산업,동일제강,동일철강,동진쎄미켐,동화기업,동화약품,두산,두산밥캣,두산중공업,두산퓨얼셀,두올,듀오백,드래곤플라이,드림시큐리티,드림씨아이에스,드림어스컴퍼니,드림텍,디딤,디바이스이엔지,디스플레이텍,디씨엠,디아이,디아이동일,디아이씨,디아이티,디아크,디알젬,디알텍,디앤디플랫폼리츠,디앤씨미디어,디에스케이,디에이치피코리아,디에이테크놀로지,디에이피,디엑스앤브이엑스,디엔에이링크,디엔에프,디오,디와이,디와이디,디와이씨,디와이파워,디와이피엔에프,디이엔티,디젠스,디지아이,디지캡,디지탈옵틱,디지털대성,디지틀조선,디케이락,디케이앤디,디케이티,디티알오토모티브,디티앤씨,딜리,딥노이드,라닉스,라온시큐어,라온테크,라온피플,라이온켐텍,라이트론,라이프시맨틱스,라파스,락앤락,래몽래인,램테크놀러지,랩지노믹스,러셀,레고켐바이오,레드로버,레드캡투어,레몬,레이,레이언스,레이크머티리얼즈,레인보우로보틱스,로보로보,로보스타,로보티즈,로스웰,로지시스,로체시스템즈,롯데관광개발,롯데렌탈,롯데리츠,롯데손해보험,롯데쇼핑,롯데정밀화학,롯데정보통신,롯데제과,롯데지주,롯데칠성음료,롯데케미칼,롯데푸드,롯데하이마트,루멘스,루트로닉,룽투코리아,리노공업,리노스,리더스 기술투자,리더스코스메틱,리드코프,리메드,리파인,릭스솔루션,린드먼아시아,링네트,링크제니시스,마니커,마니커에프앤지,마이더스ai,마이크로디지탈,마이크로컨텍솔,마이크로프랜드,마인즈랩,마크로젠,만도,만호제강,맘스터치,매일유업,매일홀딩스,매직마이크로,매커스,맥쿼리인프라,맵스리얼티1,머큐리,멀티캠퍼스,메가스터디,메가스터디교육,메가엠디,메드팩토,메디아나,메디앙스,메디콕스,메디톡스,메디포스트,메디프론,메리츠금융지주,메리츠증권,메리츠화재,메이슨캐피탈,메지온,메카로,메타랩스,메타바이오메드,멕아이씨에스,멜파스,명문제약,명성티엔에스,명신산업,모나리자,모나미,모다이노칩,모두투어,모두투어리츠,모바일리더,모바일어플라이언스,모베이스,모베이스전자,모비릭스,모비스,모아텍,모토닉,모트렉스,모헨즈,무림p&p,무림sp,무림페이퍼,무학,문배철강,미디어젠,미래나노텍,미래산업,미래생명자원,미래아이앤지,미래에셋대우스팩 5호,미래에셋대우스팩3호,미래에셋맵스리츠,미래에셋벤처투자,미래에셋생명,미래에셋증권,미래컴퍼니,미스터블루,미원상사,미원에스씨,미원홀딩스,미원화학,미창석유공업,미코,미코바이오메드,미투온,미투젠,민앤지,바다로19호,바디텍메드,바른손,바른손이앤에이,바른전자,바이넥스,바이브컴퍼니,바이오니아,바이오다인,바이오로그디바이스,바이오리더스,바이오솔루션,바이오스마트,바이오톡스텍,바이오플러스,바이온,바이옵트로,바이젠셀,바텍,박셀바이오,방림,배럴,백광산업,백금t&a,백산,버킷스튜디오,범양건영,베노홀딩스,베뉴지,베셀,베스파,베트남개발1,벽산,보광산업,보라티알,보락,보령제약,보성파워텍,보해양조,본느,부광약품,부국증권,부국철강,부방,부산산업,부산주공,부스타,뷰노,뷰웍스,브랜드엑스코퍼레이션,브레인즈컴퍼니,브리지텍,브릿지바이오,브이원텍,브이티지엠피,블루베리 nft,블루콤,블리츠웨이,비나텍,비덴트,비디아이,비보존 헬스케어,비비씨,비비안,비상교육,비씨월드제약,비아트론,비에이치,비에이치아이,비엠티,비올,비즈니스온,비츠로셀,비츠로시스,비츠로테크,비케이탑스,비투엔,비트나인,비트컴퓨터,비피도,빅솔론,빅텍,빙그레,빛샘전자,사람인에이치알,사조대림,사조동아원,사조산업,사조씨푸드,사조오양,삼강엠앤티,삼기,삼륭물산,삼목에스폼,삼보모터스,삼보산업,삼보판지,삼부토건,삼성sdi,삼성공조,삼성물산,삼성바이오로직스,삼성생명,삼성에스디에스,삼성엔지니어링,삼성전기,삼성전자,삼성제약,삼성중공업,삼성증권,삼성출판사,삼성카드,삼성화재해상보험,삼아알미늄,삼아제약,삼양사,삼양식품,삼양옵틱스,삼양통상,삼양패키징,삼양홀딩스,삼영무역,삼영에스앤씨,삼영엠텍,삼영이엔씨,삼영전자공업,삼영화학공업,삼원강재,삼익thk,삼익악기,삼일,삼일기업공사,삼일씨엔에스,삼일제약,삼정펄프,삼지전자,삼진,삼진엘앤디,삼진제약,삼천당제약,삼천리,삼천리자전거,삼표시멘트,삼현철강,삼호개발,삼화네트웍스,삼화왕관,삼화전기,삼화전자공업,삼화콘덴서공업,삼화페인트공업,상보,상상인,상상인이안제2호스팩,상상인인더스트리,상상인증권,상신브레이크,상신이디피,상신전자,상아프론테크,상지카일룸,새로닉스,새론오토모티브,샘씨엔에스,샘코,샘표,샘표식품,서남,서린바이오,서부t&d,서산,서암기계공업,서연,서연이화,서연탑메탈,서울도시가스,서울리거,서울바이오시스,서울반도체,서울식품공업,서울옥션,서울전자통신,서울제약,서원,서원인텍,서전기전,서진시스템,서진오토모티브,서플러스글로벌,서한,서호전기,서흥,서희건설,석경에이티,선광,선데이토즈,선도전기,선익시스템,선진,선진뷰티사이언스,성광벤드,성도이엔지,성문전자,성보화학,성신양회,성안,성우전자,성우테크론,성우하이텍,성창기업지주,성창오토텍,성호전자,세경하이테크,세기상사,세동,세림b&g,세명전기,세방,세방전지,세보엠이씨,세아베스틸,세아제강,세아제강지주,세아특수강,세아홀딩스,세영디앤씨,세우글로벌,세운메디칼,세원,세원물산,세원이앤씨,세원정공,세이브존i&c,세종공업,세종메디칼,세종텔레콤,세중,세진중공업,세진티에스,세코닉스,세틀뱅크,세하,세화피앤씨,센코,센트랄모텍,센트럴인사이트,셀레믹스,셀루메드,셀리드,셀리버리,셀바스ai,셀바스헬스케어,셀트리온,셀트리온제약,셀트리온헬스케어,소룩스,소리바다,소마젠,소프트센,소프트캠프,손오공,솔고바이오,솔루스첨단소재,솔루에타,솔루엠,솔본,솔브레인,솔브레인홀딩스,솔트룩스,송원산업,쇼박스,수산아이앤티,수산중공업,수성이노베이션,수젠텍,슈프리마,슈프리마아이디,슈프리마에이치큐,슈피겐코리아,스맥,스카이문스테크놀로지,스카이이앤엠,스킨앤스킨,스타플렉스,스튜디오드래곤,스튜디오산타클로스,스틱인베스트먼트,스페코,스포츠서울,승일,시공테크,시그네틱스,시너지이노베이션,시노펙스,시디즈,시스웍,시큐브,시티랩스,신대양제지,신도기연,신도리코,신라교역,신라섬유,신라에스지,신라젠,신성델타테크,신성이엔지,신성통상,신세계,신세계i&c,신세계건설,신세계인터내셔날,신세계푸드,신송홀딩스,신신제약,신영스팩5호,신영스팩6호,신영와코루,신영증권,신원,신원종합개발,신일전자,신일제약,신진에스엠,신테카바이오,신풍제약,신풍제지,신한알파리츠,신한제6호스팩,신한지주,신화인터텍,신화콘텍,신흥,신흥에스이씨,실리콘투,심텍,심텍홀딩스,싸이맥스,싸이버원,싸이토젠,쌍방울,쌍용씨앤이,쌍용자동차,쌍용정보통신,써니전자,썸에이지,쎄노텍,쎄니트,쎄트렉아이,쎌마테라퓨틱스,쎌바이오텍,쏠리드,씨씨에스,씨아이에스,씨아이테크,씨앤씨인터내셔널,씨앤지하이테크,씨앤투스성진,씨에스베어링,씨에스윈드,씨엔알리서치,씨엔플러스,씨엠에스에듀,씨유메디칼,씨유테크,씨이랩,씨젠,씨케이에이치,씨큐브,씨티씨바이오,씨티케이,아가방컴퍼니,아나패스,아난티,아남전자,아래스,아리온,아모그린텍,아모레퍼시픽,아모레퍼시픽그룹,아모센스,아모텍,아미노로직스,아미코젠,아바코,아바텍,아비코전자,아세아,아세아시멘트,아세아제지,아세아텍,아센디오,아스타,아스트,아스플로,아시아경제,아시아나idt,아시아나항공,아우딘퓨쳐스,아이디스,아이디스홀딩스,아이디피,아이마켓코리아,아이비김영,아이센스,아이스크림에듀,아이쓰리시스템,아이씨디,아이씨케이,아이앤씨,아이에스동서,아이에스이커머스,아이에이,아이에이치큐,아이엘사이언스,아이엠,아이오케이,아이원스,아이윈,아이즈비전,아이진,아이컴포넌트,아이퀘스트,아이큐어,아이크래프트,아이텍,아이톡시,아이티센,아이티아이즈,아이티엠반도체,아이패밀리에스씨,아주ib투자,아주스틸,아즈텍wb,아진산업,아진엑스텍,아톤,아프리카tv,안국약품,안랩,안트로젠,알로이스,알루코,알리코제약,알비더블유,알서포트,알에스오토메이션,알에프세미,알에프텍,알엔투테크놀로지,알체라,알테오젠,알톤스포츠,알티캐스트,알파홀딩스,압타머사이언스,압타바이오,애경산업,애경케미칼,애니젠,애니플러스,애드바이오텍,애머릿지,액션스퀘어,액토즈소프트,액트로,앤디포스,앤씨앤,앱코,앱클론,야스,얍엑스,양지사,어보브반도체,얼라인드,에너토크,에넥스,에디슨ev,에브리봇,에스넷,에스디바이오센서,에스디생명공학,에스디시스템,에스맥,에스씨디,에스씨엠생명과학,에스아이리소스,에스앤더블류,에스앤디,에스앤에스텍,에스에너지,에스에스알,에스에이엠티,에스에이티,에스에이티이엔지,에스에프에이,에스엔유,에스엘,에스엘바이오닉스,에스엠,에스엠코어,에스와이,에스원,에스제이그룹,에스제이엠,에스제이엠홀딩스,에스케이바이오팜,에스코넥,에스텍,에스텍파마,에스트래픽,에스티아이,에스티오,에스티큐브,에스티팜,에스폴리텍,에스퓨얼셀,에스피시스템스,에스피지,에쎈테크,에쓰씨엔지니어링,에어부산,에이디엠코리아,에이디칩스,에이디테크놀로지,에이루트,에이리츠,에이블씨엔씨,에이비엘바이오,에이비온,에이비프로바이오,에이스침대,에이스테크,에이스토리,에이에프더블류,에이엔피,에이치시티,에이치앤비디자인,에이치엔티,에이치엘비파워,에이치엘사이언스,에이치엠씨제4호스팩,에이치엠씨제5호스팩,에이치케이,에이치피오,에이테크솔루션,에이텍,에이텍티앤,에이트원,에이티넘인베스트,에이티세미콘,에이팩트,에이프로,에이프로젠 h&g,에이프로젠 med,에이프로젠제약,에이플러스에셋,에이피티씨,에치에프알,에코마케팅,에코바이오,에코캡,에코프로,에코프로비엠,에코플라스틱,에프알텍,에프앤가이드,에프앤리퍼블릭,에프에스티,에프엔씨엔터,에프엔에스테크,엑사이엔씨,엑세스바이오,엑셈,엑스큐어,엑시콘,엔바이오니아,엔브이에이치코리아,엔비티,엔시스,엔시트론,엔씨소프트,엔에스,엔에스쇼핑,엔에스엔,엔에이치스팩18호,엔에이치엔,엔에프씨,엔젠바이오,엔지스테크널러지,엔지켐생명과학,엔케이,엔케이맥스,엔켐,엔텔스,엔투텍,엔피,엔피디,엔피씨,엔피케이,엘디티,엘브이엠씨,엘비루셈,엘비세미콘,엘아이에스,엘앤씨바이오,엘앤에프,엘앤케이바이오,엘에스일렉트릭,엘엠에스,엘오티베큠,엘컴텍,엘티씨,엠게임,엠로,엠벤처투자,엠브레인,엠씨넥스,엠아이텍,엠에스씨,엠에스오토텍,엠에프엠코리아,엠케이전자,엠투아이,엠투엔,엠플러스,엠피대산,연우,연이비앤티,영림원소프트랩,영보화학,영신금속,영우디에스피,영원무역,영원무역홀딩스,영진약품,영풍,영풍정밀,영풍제지,영화금속,영화테크,영흥,예림당,예선테크,예스24,예스코홀딩스,예스티,오가닉티코스메틱,오공,오디텍,오뚜기,오로라,오로스테크놀로지,오르비텍,오리엔탈정공,오리엔트바이오,오리엔트정공,오리온,오리온홀딩스,오리콤,오비고,오상자이엘,오성첨단소재,오션브릿지,오스코텍,오스테오닉,오스템,오스템임플란트,오이솔루션,오킨스전자,오텍,오토앤,오파스넷,오픈베이스,오하임아이엔티,올리패스,올릭스,옴니시스템,옵트론텍,옵티시스,옵티팜,와이더플래닛,와이솔,와이아이케이,와이어블,와이엔텍,와이엠씨,와이엠텍,와이엠티,와이오엠,와이제이엠게임즈,와이즈버즈,와이지-원,와이지엔터테인먼트,와이투솔루션,와이팜,와토스코리아,용평리조트,우리금융지주,우리기술,우리기술투자,우리넷,우리들휴브레인,우리로,우리바이오,우리산업,우리산업홀딩스,우리손에프앤지,우리이앤엘,우리조명,우리종금,우림피티에스,우성,우수ams,우신시스템,우양,우원개발,우정바이오,우주일렉트로,우진,우진비앤지,우진아이엔에스,우진플라임,웅진,웅진씽크빅,원림,원바이오젠,원방테크,원익,원익ips,원익qnc,원익머트리얼즈,원익큐브,원익피앤이,원익홀딩스,원일특강,원풍,원풍물산,월덱스,웨이브일렉트로,웰바이오텍,웰크론,웰크론한텍,웹스,웹젠,웹케시,위니아딤채,위닉스,위더스제약,위드텍,위메이드,위메이드맥스,위세아이텍,위즈코프,위지윅스튜디오,위지트,윈스,윈텍,윈팩,윈하이텍,윌링스,윌비스,윙입푸드,유나이티드,유네코,유니드,유니셈,유니슨,유니온,유니온머티리얼,유니온커뮤니티,유니켐,유니퀘스트,유니크,유니테스트,유니테크노,유니트론텍,유라테크,유바이오로직스,유비벨록스,유비케어,유비쿼스,유비쿼스홀딩스,유성기업,유성티엔에스,유수홀딩스,유신,유아이디,유아이엘,유안타제5호스팩,유안타제7호스팩,유안타증권,유앤아이,유에스티,유엔젤,유유제약,유일에너테크,유진기업,유진로봇,유진증권,유진테크,유테크,유티아이,유틸렉스,유한양행,유화증권,육일씨엔에쓰,율촌화학,율호,이건산업,이건홀딩스,이구산업,이글루시큐리티,이글벳,이노뎁,이노메트리,이노션,이노와이어리스,이노인스트루먼트,이노테라피,이녹스,이녹스첨단소재,이니텍,이더블유케이,이라이콤,이랜시스,이랜텍,이루다,이루온,이리츠코크렙,이마트,이미지스,이베스트스팩5호,이베스트이안스팩1호,이베스트투자증권,이브이첨단소재,이삭엔지니어링,이상네트웍스,이수앱지스,이수페타시스,이수화학,이스타코,이스트소프트,이스트아시아홀딩스,이씨에스,이아이디,이엔드디,이엔에프테크놀로지,이엔코퍼레이션,이엔플러스,이엘피,이엠넷,이엠앤아이,이엠코리아,이엠텍,이연제약,이오테크닉스,이오플로우,이원컴포텍,이월드,이즈미디어,이지바이오,이지스레지던스리츠,이지스밸류플러스리츠,이지케어텍,이지홀딩스,이큐셀,이크레더블,이트론,이퓨쳐,이화공영,이화산업,이화전기,인디에프,인바디,인바이오,인바이오젠,인베니아,인산가,인선이엔티,인성정보,인스코비,인지디스플레,인지컨트롤스,인천도시가스,인콘,인크로스,인탑스,인터로조,인터엠,인터지스,인터파크,인터플렉스,인텍플러스,인텔리안테크,인트로메딕,인트론바이오,인팩,인포마크,인포바인,인포뱅크,인피니트헬스케어,인피니티엔티,인화정공,일동제약,일동홀딩스,일성건설,일성신약,일승,일신바이오,일신방직,일신석재,일야,일양약품,일정실업,일지테크,일진다이아,일진디스플,일진머티리얼즈,일진전기,일진파워,일진하이솔루스,일진홀딩스,잇츠한불,잉글우드랩,잉크테크,자비스,자연과환경,자이글,자이언트스텝,자이에스앤디,자화전자,장원테크,재영솔루텍,전방,전진바이오팜,정다운,정산애강,정상제이엘에스,정원엔시스,제너셈,제넥신,제넨바이오,제노레이,제노코,제노포커스,제놀루션,제닉,제로투세븐,제룡산업,제룡전기,제우스,제이브이엠,제이스텍,제이시스메디칼,제이씨케미칼,제이씨현시스템,제이알글로벌리츠,제이앤티씨,제이에스코퍼레이션,제이에스티나,제이엔케이히터,제이엘케이,제이엠아이,제이엠티,제이웨이,제이준코스메틱,제이콘텐트리,제이티,제일기획,제일바이오,제일약품,제일연마,제일전기공업,제일제강,제일테크노스,제일파마홀딩스,제주맥주,제주반도체,제주은행,제주항공,제테마,젠큐릭스,젬백스,젬백스링크,젬백스지오,조광ili,조광페인트,조광피혁,조비,조선내화,조선선재,조아제약,조이시티,조일알미늄,조흥,종근당,종근당바이오,종근당홀딩스,좋은사람들,주성엔지니어링,주연테크,줌인터넷,중앙디앤엠,중앙백신,중앙에너비스,지나인제약,지노믹트리,지놈앤컴퍼니,지누스,지니뮤직,지니언스,지니틱스,지더블유바이텍,지란지교시큐리티,지스마트글로벌,지씨셀,지아이텍,지앤비에스엔지니어링,지어소프트,지에스이,지엔씨에너지,지엔원에너지,지엔코,지엘팜텍,지엠비코리아,지역난방공사,지오엘리먼트,지코,지투알,지티지웰니스,진도,진로발효,진매트릭스,진바이오텍,진성티이씨,진양산업,진양제약,진양폴리우레탄,진양홀딩스,진양화학,진에어,진원생명과학,진흥기업,차바이오텍,참엔지니어링,참존글로벌,참좋은여행,창해에탄올,천보,천일고속,청담러닝,체리부로,체시스,초록뱀미디어,초록뱀컴퍼니,칩스앤미디어,카스,카이노스메드,카카오,카카오게임즈,카카오뱅크,카카오페이,카페24,카프로,캐리소프트,캐스텍코리아,캠시스,컨버즈,컬러레이,컴투스,컴투스홀딩스,컴퍼니케이,케어랩스,케어젠,케이디켐,케이비아이동국실업,케이비제18호스팩,케이비제19호스팩,케이비제20호스팩,케이사인,케이씨,케이씨씨,케이씨씨글라스,케이씨에스,케이씨텍,케이씨티,케이씨티시,케이씨피드,케이아이엔엑스,케이에스피,케이엔더블유,케이엔제이,케이엘넷,케이엠,케이엠더블유,케이엠제약,케이옥션,케이카,케이탑리츠,케이티,케이티비네트워크,케이티스카이라이프,케이티알파,케이티앤지,케이프,케이프이에스제4호,케이피에스,케이피에프,케이피엠테크,케이피티유,켄코아에어로스페이스,켐온,켐트로닉스,켐트로스,코나아이,코다코,코데즈컴바인,코드네이처,코디,코디엠,코람코에너지리츠,코렌텍,코리아나,코리아센터,코리아써키트,코리아에셋투자증권,코리아에스이,코리아에프티,코리안리,코맥스,코메론,코미코,코미팜,코세스,코센,코스나인,코스맥스,코스맥스비티아이,코스맥스엔비티,코스메카코리아,코스모신소재,코스모화학,코스온,코아스,코아스템,코아시아,코아시아옵틱스,코엔텍,코오롱,코오롱글로벌,코오롱생명과학,코오롱인더,코오롱티슈진,코오롱플라스틱,코웨이,코웰패션,코위버,코윈테크,코이즈,코콤,코텍,코퍼스코리아,코프라,콜마비앤에이치,콤텍시스템,쿠콘,쿠쿠홀딩스,쿠쿠홈시스,퀀타매트릭스,큐라클,큐렉소,큐로,큐로컴,큐로홀딩스,큐리언트,큐브엔터,큐에스아이,큐캐피탈,크라운제과,크라운해태홀딩스,크래프톤,크로바하이텍,크루셜텍,크리스에프앤씨,크리스탈신소재,크리스탈지노믹스,크린앤사이언스,클라우드에어,클래시스,클리노믹스,클리오,키네마스터,키다리스튜디오,키움증권,키이스트,타이거일렉,탑엔지니어링,탑코미디어,태경비케이,태경산업,태경케미컬,태광,태광산업,태림포장,태양,태양금속공업,태영건설,태웅,태웅로직스,태원물산,태평양물산,테고사이언스,테라사이언스,테라셈,테라젠이텍스,테스,테스나,테이팩스,테크윙,텔레칩스,텔레필드,텔코웨어,텔콘rf제약,토니모리,토박스코리아,토비스,토탈소프트,톱텍,투비소프트,툴젠,트루윈,트윔,특수건설,티라유텍,티로보틱스,티비씨,티비에이치글로벌,티사이언티픽,티씨케이,티앤알바이오팹,티앤엘,티에스아이,티에스이,티에이치엔,티엘비,티엘아이,티와이홀딩스,티움바이오,티웨이항공,티웨이홀딩스,티케이케미칼,티플랙스,티피씨글로벌,팅크웨어,파나진,파나케이아,파라다이스,파라텍,파루,파마리서치,파멥신,파미셀,파버나인,파세코,파수,파워넷,파워로직스,파이오링크,파인디앤씨,파인디지털,파인테크닉스,파인텍,파커스,파크시스템스,파트론,판타지오,팜스빌,팜스코,팜스토리,팜젠사이언스,패션플랫폼,팬스타엔터프라이즈,팬엔터테인먼트,팬오션,팬젠,퍼스텍,퍼시스,펄어비스,펌텍코리아,페이퍼코리아,펩트론,평화산업,평화홀딩스,포메탈,포스코,포스코 ict,포스코강판,포스코엠텍,포스코인터내셔널,포스코케미칼,포시에스,포인트모바일,포인트엔지니어링,포커스에이치엔에스,포티스,폴라리스오피스,폴라리스우노,폴라리스웍스,폴루스바이오팜,푸드나무,푸드웰,푸른기술,푸른저축은행,풀무원,풍강,풍국주정,풍산,풍산홀딩스,퓨쳐켐,프럼파스트,프레스티지바이오로직스,프로스테믹스,프로이천,프로텍,프롬바이오,프리시젼바이오,프리엠스,플랜티넷,플레이그램,플레이디,플레이위드,플리토,피델릭스,피씨디렉트,피씨엘,피앤씨테크,피에스엠씨,피에스케이,피에스케이홀딩스,피에스텍,피에이치씨,피에이치에이,피엔에이치테크,피엔케이피부임상연구센타,피엔티,피제이메탈,피제이전자,피코그램,피플바이오,피피아이,픽셀플러스,필옵틱스,핌스,핑거,하나금융14호스팩,하나금융15호스팩,하나금융16호스팩,하나금융지주,하나기술,하나마이크론,하나머티리얼즈,하나제약,하나투어,하림,하림지주,하이골드3호,하이로닉,하이록코리아,하이브,하이비젼시스템,하이소닉,하이스틸,하이제5호스팩,하이즈항공,하이텍팜,하이트론씨스템즈,하이트진로,하이트진로홀딩스,하츠,한국가구,한국가스공사,한국경제tv,한국공항,한국금융지주,한국기업평가,한국내화,한국단자공업,한국맥널티,한국바이오젠,한국비엔씨,한국석유공업,한국선재,한국수출포장공업,한국쉘석유,한국알콜,한국앤컴퍼니,한국유니온제약,한국자산신탁,한국전력공사,한국전자금융,한국전자인증,한국전자홀딩스,한국정밀기계,한국정보공학,한국정보인증,한국정보통신,한국조선해양,한국종합기술,한국주강,한국주철관공업,한국철강,한국카본,한국캐피탈,한국컴퓨터,한국코퍼레이션,한국콜마,한국콜마홀딩스,한국큐빅,한국타이어앤테크놀로지,한국테크놀로지,한국토지신탁,한국특강,한국파마,한국팩키지,한국프랜지공업,한국항공우주,한국화장품,한국화장품제조,한글과컴퓨터,한네트,한농화성,한독,한독크린텍,한라,한라ims,한라홀딩스,한미글로벌,한미반도체,한미사이언스,한미약품,한빛소프트,한샘,한섬,한성기업,한세실업,한세엠케이,한세예스24홀딩스,한솔로지스틱스,한솔인티큐브,한솔제지,한솔케미칼,한솔테크닉스,한솔피엔에스,한솔홀딩스,한솔홈데코,한송네오텍,한스바이오메드,한신공영,한신기계공업,한양디지텍,한양이엔지,한양증권,한온시스템,한올바이오파마,한익스프레스,한일네트웍스,한일단조,한일사료,한일시멘트,한일진공,한일철강,한일현대시멘트,한일홀딩스,한일화학,한전kps,한전기술,한전산업,한진,한진중공업홀딩스,한진칼,한창,한창바이오텍,한창산업,한창제지,한컴mds,한컴라이프케어,한컴위드,한탑,한프,한화,한화생명,한화손해보험,한화솔루션,한화시스템,한화에어로스페이스,한화투자증권,해성디에스,해성산업,해성옵틱스,해성티피씨,해태제과식품,핸디소프트,핸즈코퍼레이션,헝셩그룹,헬릭스미스,현대건설,현대건설기계,현대공업,현대그린푸드,현대글로비스,현대두산인프라코어,현대로템,현대리바트,현대모비스,현대무벡스,현대미포조선,현대바이오,현대바이오랜드,현대백화점,현대비앤지스틸,현대사료,현대약품,현대에너지솔루션,현대에버다임,현대에이치티,현대엘리베이터,현대오토에버,현대위아,현대이지웰,현대일렉트릭,현대자동차,현대제철,현대중공업,현대중공업지주,현대차증권,현대코퍼레이션,현대코퍼레이션홀딩스,현대퓨처넷,현대해상,현대홈쇼핑,현우산업,현진소재,협진,형지i&c,형지엘리트,혜인,호전실업,호텔신라,홈센타홀딩스,홈캐스트,화성밸브,화성산업,화승엔터프라이즈,화승인더스트리,화승코퍼레이션,화신,화신정공,화인베스틸,화일약품,화천기계,화천기공,환인제약,황금에스티,효성,효성 itx,효성오앤비,효성중공업,효성첨단소재,효성티앤씨,효성화학,후성,휘닉스소재,휠라홀딩스,휴네시온,휴니드테크놀러지스,휴럼,휴림로봇,휴마시스,휴맥스,휴맥스홀딩스,휴먼엔,휴메딕스,휴비스,휴비츠,휴센텍,휴스틸,휴온스,휴온스글로벌,휴온스블러썸,휴젤,휴켐스,흥구석유,흥국,흥국에프엔비,흥국화재,흥아해운,희림,힘스,

In [6]:
for i in tqdm(it):
    cursor.execute(
    """
        insert into tmp select `{}`.* from `{}`;
    """.format(i,i))

100%|██████████| 2308/2308 [03:27<00:00, 11.13it/s]

In [38]:
[cursor.execute(
    """
        insert into tmp select `{}`.* from `{}`;
    """.format(i,i)
    ) for i in tqdm(it)]
# cursor.execute(
#     """
#         insert into tmp select {}.* from {};
#     """.format(i,i)
#     )

KeyboardInterrupt:

In [27]:
cursor.execute('truncate table tmp;')

0

In [9]:
# conn.rollback()
conn.commit()

In [20]:
df_['TABLE_NAME'].unique()

array(['3s', 'aj네트웍스', 'ak홀딩스', ..., '흥아해운', '희림', '힘스'], dtype=object)

In [8]:
conn.commit()

cursor.execute(
    "select * from tmp;"
)

col = cursor.description
col_list = [col[i][0] for i in range(len(col))]
res = pd.DataFrame(cursor.fetchall(),columns = col_list)

res

,corp_cls,corp_code,corp_name,detail_type,flr_nm,rcept_dt,rcept_no,report_nm,rm,stock_code,...,code1_info,key_word,remark,bs_a,bs_l,bs_k,is_r,is_c,remark_1,identifier
0,K,346911,아이톡시,대규모내부거래관련,아이톡시,20180102,20171229000947,특수관계인에대한출자,공,52770,...,Affiliated persons(특수관계인),특수관계인 지배구조(출자 등) 관련,"AFF(특수관계인) + 활동(B, A 등) 조합으로 코드 선정",None,None,None,None,None,None,201712290009471
1,Y,156859,KTB투자증권,주식등의대량보유상황보고서,이병철,20180102,20180102000004,주식등의대량보유상황보고서(일반),None,30210,...,"S(지분 변동, Stock Share)",주식 등 대량 소유 보유 상황보고,None,None,None,None,None,None,None,201801020000041
2,K,910840,윈하이텍,임원ㆍ주요주주특정증권등소유상황보고서,변천섭,20180102,20180102000005,임원ㆍ주요주주특정증권등소유상황보고서,None,192390,...,"S(지분 변동, Stock Share)",임원 등 주요주주 특정 소유 상황 변동,None,None,None,None,None,None,None,201801020000051
3,K,1010642,지씨셀,임원ㆍ주요주주특정증권등소유상황보고서,박종섭,20180102,20180102000016,임원ㆍ주요주주특정증권등소유상황보고서,None,144510,...,"S(지분 변동, Stock Share)",임원 등 주요주주 특정 소유 상황 변동,None,None,None,None,None,None,None,201801020000161
4,K,1010642,지씨셀,임원ㆍ주요주주특정증권등소유상황보고서,전용하,20180102,20180102000018,임원ㆍ주요주주특정증권등소유상황보고서,None,144510,...,"S(지분 변동, Stock Share)",임원 등 주요주주 특정 소유 상황 변동,None,None,None,None,None,None,None,201801020000181
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268005,K,245898,아래스,수시공시,아래스,20201231,20201231900517,전환사채(해외전환사채포함)발행후만기전사채취득(제1회차),코,50320,...,부채(Liability)_중 신종채권 관련,전환사채의 발행 후 만기전 재취득,None,None,None,None,None,None,None,202012319005171
268006,K,245898,아래스,수시공시,아래스,20201231,20201231900529,전환사채(해외전환사채포함)발행후만기전사채취득(제1회차),코,50320,...,부채(Liability)_중 신종채권 관련,전환사채의 발행 후 만기전 재취득,None,None,None,None,None,None,None,202012319005291
268007,K,219848,서희건설,수시공시,서희건설,20201231,20201231900539,단일판매ㆍ공급계약체결(자율공시),코정,35890,...,매출 및 수입(Sales & Revenues),단일 판매 및 공급 계약 관련,None,None,None,None,None,None,None,202012319005391
268008,K,270113,멕아이씨에스,수시공시,멕아이씨에스,20201231,20201231900546,단일판매ㆍ공급계약체결,코정,58110,...,매출 및 수입(Sales & Revenues),단일 판매 및 공급 계약 관련,None,None,None,None,None,None,None,202012319005461
268009,K,402989,코스온,수시공시,코스온,20201231,20201231900559,타법인주식및출자증권처분결정,코,69110,...,"지배, 소유구조(Governance&Ownership)",타법인 주식(출자증권) 처분 결정,None,None,None,None,None,None,None,202012319005591